name: Manually Trigger Traffic For Int Env

on:
  
  workflow_dispatch:
    inputs:
      TRAFFIC:
        description: 'Traffic: low or high'
        required: true
        default: high
        options:
          - low
          - high

jobs:
  ManualTriggerScheduler:
    uses: Preheater/.github/workflows/template.yml@main
